### ISSUE TITLE
Naming convention for base period (ES_att_contemp) makes it very hard to plot the baseperiod with event_plot command

### ISSUE THREAD

**Issue by Mbjoerkh** [thegland/wooldid#2]
Hi, 

Thanks for making this package! 

I am not able to include the baseperiod when attempting to plot the results using the event_plot command. This is because that command requires the leads and lags to follow a consistent naming convention, which wooldid does except for the contemporary effect (ES_att_contemp). 

I realize this is as much an issue for the event_plot command as it is for wooldid (I'll post an issue with them as well), but would it be possible to make an option of naming the contemporary effect "post0"? 

I would have thought it would be relatively easy to rename the matrix element but I've tried quite a few approaches without being able to do it, so adding example code for how to do that would be another option. 

`wooldid Y i t ttre, espre(10) espost(21) 

* try plotting with event_plot
event_plot  , stub_lag(ES_att_post#) stub_lead(ES_att_pre#)`

Thank you so much!

**Comment by thegland** [comment]
Hi;

I hadn't looked at compatibility with event_plot before; thanks for flagging this. I updated wooldid to use your suggested _post0_ naming scheme, but added an option (_oldsyntax_) to use the old naming scheme (i.e., the suffix _contemp_ is used rather than  _post0_) in case anybody has code that relies on it. The help files have also been updated to note this change and to explain how to use event_plot with the program.

One thing I would note is that I don't think event_plot gives you the option to add a "0" observation to your event plot, to correspond with the reference period in the analysis. Depending on one's point of view, that might not be a problem. But I personally like including the reference period on the event study plot, and wooldid will add a reference period to any event plot it generates. So, I would just keep that issue in mind. If you want the reference period to appear in your event study plots but don't want to use wooldid's defaults, you may wish to consider using _svmat_ to push one of wooldid's output matrices into memory (thus giving you a dataset where each row specifies a year relative to treatment plus the coefficient, CI, etc. for that time period) are and just make the plots that way.

Thomas

**Comment by Mbjoerkh** [comment]
Excellent - thanks for the fast update!

And also for flagging the issue with event_plot not plotting reference periods. I definitely share the view that they should be included, as that makes everything so much easier to  interpret!

**Comment by Mbjoerkh** [comment]
After looking more into the base-period issue, it seems that event_plot would include them if the estimator produces them as part of the output (in the wooldid case a pre1 coefficient of 0 with no CI's, etc.). Would you consider adding an option to include a base period element to the output as well? 

Again, I realize these are features that might be most easily incorporated through the plotting package (and I'm sure some packages have done so), but it also wouldn't surprise me if adding this as an option would make the output easier to use regardless how one is planning on plotting the event-studies.

In any case, thanks again!

**Comment by thegland** [comment]
Yeah, I can put that on my agenda to add for the future, though I don't have the time to make that adjustment for a few weeks. It would take some extra work relative to the name change alone because of how the contents of the returned results interact with wooldid's built-in event study plot production tools (which, right now, will be confused to see faux-estimates representing the reference period among the results).

-Thomas
