### ISSUE TITLE
Helpfile clarification (hdidregress and/or xthdidregress)

### ISSUE THREAD

**Issue by Mbjoerkh** [thegland/wooldid#3]
Hi again Thomas, 

This may have been on purpose, but if not, I just wanted to make you aware that your helpfile is comparing wooldid estimates to hdidregress (made for repeated cross-sectional data), when I would think most users would use the **xt**hdidregress. 

I did a quick test with and am getting identical estimates for xthdidregress and hdidregress with the below code, but wanted to flag it in case this wasn't intentional and there are times where the distinction would matter. 

`
xthdidregress twfe (Y ) (D) , group(i) vce(cluster i) hettype(timecohort) 

hdidregress twfe (Y ) (D) , group(i) **time(t)** vce(cluster i) hettype(timecohort)
`

**Comment by thegland** [comment]
I think it's fair to say that xthdidregress is probably the right point of comparison in a number of circumstances, though I am not sure about all. I tested against hdidregress because I think it is a bit more general. That said, I think you are right that the two estimators should deliver similar results in a panel setting.

As a general matter, for comparing to wooldid, I would stress two things. First, like hdidregress, wooldid does not require that you have panel data: when specifying the command _wooldid y i t ttre_, you can have more than one observation per each unique level of _i_ X _t_. So, wooldid's _i_ and _t_ variables need not be the same variables you would use when issuing an _xtset_ command. In fact, with large datasets, they rarely should be. Relatedly, wooldid can accomodate repeated cross-section data. 

As for why this is the case. In wooldid, the _i_ variable specifies groups of observations by which you want to estimate heterogenous treatment effects.  Wooldridge's underlying paper indicates that, at minimum, your _i_ variable needs to group observations by date of treatment onset (grouping never treated units into their own group as well). You can allow for more heterogeneity than that if you wish, but you don't have to go all the way to allowing unit-level treatment effect heterogeneity. For example, if you had a panel of 1 million people observed over time, estimating unique treatment effects for all of those people would likely be computationally impractical, so you would likely want to group them (perhaps by date of treatment onset, or perhaps by some other factor like state of residence). If you would want unit fixed effects in the analysis in that case, you would then need to specify their inclusion as fixed effects using the fe() option in wooldid.
